refactor: added commit lint check

diff --git a/.github/workflows/backend-ci.yml b/.github/workflows/backend-ci.yml
--- a/.github/workflows/backend-ci.yml
+++ b/.github/workflows/backend-ci.yml
@@ -8,6 +8,18 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Validate commit title
+        shell: bash
+        run: |
+          message=$(git log -1 --format=%s)
+          pattern='^(feat|chore|refactor|fix|perf|docs)(\([^()[:space:]]+\))?: [^[:space:]].*$'
+
+          if [[ ! "$message" =~ $pattern ]]; then
+            echo "Invalid commit title."
+            echo "Expected: <type>: <message> or <type>(<scope>): <message>"
+            echo "Allowed types: feat, chore, refactor, fix, perf, docs"
+            exit 1
+          fi
       - uses: actions/checkout@v4
       - name: Set up JDK 21
         uses: actions/setup-java@v4
@@ -17,18 +29,6 @@ jobs:
           cache: maven
       - name: Build with Maven
         run: mvn -B package --file pom.xml
-      - name: Validate commit title
-        shell: bash
-        run: |
-          message=$(git log -1 --format=%s)
-          pattern='^(feat|chore|refactor|fix|perf|docs)(\([^()[:space:]]+\))?: [^[:space:]].*$'
-          
-          if [[ ! "$message" =~ $pattern ]]; then
-            echo "Invalid commit title."
-            echo "Expected: <type>: <message> or <type>(<scope>): <message>"
-            echo "Allowed types: feat, chore, refactor, fix, perf, docs"
-            exit 1
-          fi
 
       # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
       - name: Update dependency graph
